// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcn1LWJL_OJd76lGdwVCswffqHa6etXiw',
    appId: '1:152280502218:web:a53204b5930bf168e9c933',
    messagingSenderId: '152280502218',
    projectId: 'mozchatapp',
    authDomain: 'mozchatapp.firebaseapp.com',
    storageBucket: 'mozchatapp.firebasestorage.app',
    measurementId: 'G-N0N1EF1NYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG0rubgCUB3PwAY7ZyGM48WuA4xQo0yF8',
    appId: '1:152280502218:android:4abb33cc57239746e9c933',
    messagingSenderId: '152280502218',
    projectId: 'mozchatapp',
    storageBucket: 'mozchatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgTvXK7tzpXCXlKN1Jre5QXc_bxgxdSas',
    appId: '1:152280502218:ios:524c46fb75912c0ae9c933',
    messagingSenderId: '152280502218',
    projectId: 'mozchatapp',
    storageBucket: 'mozchatapp.firebasestorage.app',
    iosBundleId: 'com.example.mozChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgTvXK7tzpXCXlKN1Jre5QXc_bxgxdSas',
    appId: '1:152280502218:ios:0fbae93ce4d6af62e9c933',
    messagingSenderId: '152280502218',
    projectId: 'mozchatapp',
    storageBucket: 'mozchatapp.firebasestorage.app',
    iosBundleId: 'com.mozChat.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcn1LWJL_OJd76lGdwVCswffqHa6etXiw',
    appId: '1:152280502218:web:10309669c275f57de9c933',
    messagingSenderId: '152280502218',
    projectId: 'mozchatapp',
    authDomain: 'mozchatapp.firebaseapp.com',
    storageBucket: 'mozchatapp.firebasestorage.app',
    measurementId: 'G-7JX40Z3P2T',
  );
}
